### ISSUE TITLE
大佬请问这个错误怎么搞，没有百度到

### ISSUE THREAD

**Issue by CollinsWalker** [JalenChuh/baidu-url-submit-by-using-sitemap#3]
提示这个：“Error
Only actions in "CollinsWalker" are allowed for this repository”

说是只能允许我的名字运行这个仓库

**Comment by jalenchuh** [comment]
在仓库的 `Setting > Action` 中选择 `Enable local and third party Actions for this repository `，应该能解决

**Comment by jalenzz** [comment]
@CollinsWalker 在仓库的 `Setting > Action` 中选择 `Enable local and third party Actions for this repository`，应该能解决

**Comment by CollinsWalker** [comment]
> Enable local and third party Actions for this repository

好的，我试试，谢谢

**Comment by jalenzz** [comment]
@CollinsWalker 看了下你那个仓库，Action 报错 `HTTP Error 403: Forbidden`，应该是你网站禁止爬取

**Comment by CollinsWalker** [comment]
> @CollinsWalker 看了下你那个仓库，Action 报错 `HTTP Error 403: Forbidden`，应该是你网站禁止爬取

哦哦，我也不太清楚，我一直再找原因
