### ISSUE TITLE
你的sitemap.xml是用什么生成的

### ISSUE THREAD

**Issue by gaoxianghua** [jalenchuh/baidu-url-submit-by-using-sitemap#5]
你的sitemap.xml是用什么工具生成的，我的貌似会提示根节点不合法，listenlive.cn/sitemap.xml

**Comment by jalenchuh** [comment]
你的 sitemap 结构不同，已经发起 PR https://github.com/gaoxianghua/baidu-url-submit-by-using-sitemap/pull/1
